name: Build and Distribute Android App

on:
  push:
    branches:
      - main # Substitua pela branch que deseja monitorar

jobs:
  build:
    name: Build and Distribute
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurar o JDK
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11' # Substitua pela versão do JDK que seu projeto usa

      # Cache do Gradle
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Build do aplicativo Android
      - name: Build the app
        run: ./gradlew assembleRelease # Substitua por assembleDebug se for um build de debug

#      # Upload do APK/AAB para o Firebase
#      - name: Upload to Firebase
#        env:
#          FIREBASE_AUTH_TOKEN: ${{ secrets.FIREBASE_AUTH_TOKEN }} # Configure este secret no repositório
#        run: |
#          firebase appdistribution:distribute \
#          app/build/outputs/apk/release/app-release.apk \ # Substitua pelo caminho correto do APK/AAB
#          --app <FIREBASE_APP_ID> \ # Substitua pelo ID do seu app no Firebase
#          --groups testers # Substitua pelo grupo de testers configurado no Firebase